- name: Disable swap #because of https://github.com/kubernetes/kubernetes/issues/53533
  become: yes
  shell: swapoff -a

- name: Create /etc/modules-load.d/containerd.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

- name: Load overlay kernel module
  become: yes
  command: modprobe overlay

- name: Load br_netfilter kernel module
  become: yes
  command: modprobe br_netfilter

- name: Create /etc/sysctl.d/99-kubernetes-k8s.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes-k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply kernel parameters
  become: yes
  command: sysctl --system

- name: Install containerd
  become: yes
  apt:
    name: containerd

- name: Generate containerd config
  become: yes
  command: containerd config default > /etc/containerd/config.toml

- name: Add SystemdCgroup to /etc/containerd/config.toml
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    insertafter: '^[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options]$'
    line: '    SystemdCgroup = true'
    state: present
    backup: true

- name: Enable containerd service
  become: yes
  ansible.builtin.systemd:
    name: containerd
    enabled: true

- name: Restart containerd service
  become: yes
  ansible.builtin.systemd:
    name: containerd
    state: restarted