- name: Retrieve K3s Token from the main node
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  delegate_to: "{{ groups['main-node'][0] }}"
  register: token_file
  become: true

- name: Decode the token and remove trailing newline
  ansible.builtin.set_fact:
    token_decoded: "{{ token_file.content | b64decode | replace('\n', '') }}"

- name: Install K3s and join cluster
  ansible.builtin.shell:
    cmd: curl -sfL https://get.k3s.io | K3S_URL=https://{{ main_node_static_ip }}:6443 K3S_TOKEN={{ token_decoded }} sh -
  become: yes