#- name: Setup external disk(USB stick)
#  hosts: magi[0]
#  become: yes
#  tasks:
#    - name: Gather facts
#      ansible.builtin.setup:
#
#    - name: Configure automatic disk mount
#      become: yes
#      ansible.builtin.lineinfile:
#        path: /etc/fstab
#        line: '/dev/sda1 /mnt/usb auto defaults,user 0 1'
#        state: present
#
#    - name: Install nfs-kernel-server
#      become: yes
#      apt:
#        name: nfs-kernel-server
#
#    - name: Ensure a mount point exists
#      become: yes
#      ansible.builtin.file:
#        path: /mnt/usb/scratch
#        state: directory
#        owner: anton
#        group: anton
#        mode: '0755'
#
#    - name: Setup symlink
#      become: yes
#      ansible.builtin.command:
#        cmd: ln -s /mnt/usb/scratch /scratch
#
#    - name: Allow cluster subnet to mount the disk
#      become: yes
#      ansible.builtin.lineinfile:
#        path: /etc/exports
#        line: '/mnt/usb/scratch {{ cluster_subnet }}/24(rw,sync)'
#        state: present
#        create: yes
#
#    - name: Enable and restart rpcbind.service
#      ansible.builtin.service:
#        name: rpcbind
#        state: restarted
#        enabled: yes
#
#    - name: Enable and restart nfs-server.service
#      ansible.builtin.service:
#        name: nfs-server
#        state: restarted
#        enabled: yes