- name: Kubernetes setup
  hosts: magi
  become: yes
  tasks:
    - include_tasks: tasks/update_upgrade.yaml

    - name: Disable swap #because of https://github.com/kubernetes/kubernetes/issues/53533
      shell: swapoff -a

    - name: Create /etc/modules-load.d/containerd.conf
      ansible.builtin.copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay kernel module
      command: modprobe overlay

    - name: Load br_netfilter kernel module
      command: modprobe br_netfilter

    - name: Create /etc/sysctl.d/99-kubernetes-k8s.conf
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply kernel parameters
      command: sysctl --system

    - name: Install containerd
      apt:
        name: containerd

    - name: Generate containerd config
      command: containerd config default > /etc/containerd/config.toml

    - name: Add SystemdCgroup to /etc/containerd/config.toml
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        insertafter: '^[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options]$'
        line: '    SystemdCgroup = true'
        state: present
        backup: true

    - name: Enable containerd service
      ansible.builtin.systemd:
        name: containerd
        enabled: true

    - name: Restart containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted


